### ISSUE TITLE
FFMpeg最新已经到7.0了，有升级计划吗？

### ISSUE THREAD

**Issue by peerless2012** [ShikinChen/ijkplayer-android#1]

**Comment by ShikinChen** [comment]
可能等我有空在升级 b站是改动过ffmpeg 需要对官方源码进行一定修改

**Comment by peerless2012** [comment]
是的，我也在b站基础上改了ffmpeg，不过还好改的不多。其实我都有点想弃坑了，转去用VLC了。

**Comment by ShikinChen** [comment]
已经有升级到7.1分支 7.1的api改动有点大 旧的api全部在7.1删除了,所以需要改成新的api 怕出问题单独开一个分支

**Comment by peerless2012** [comment]
iOS端也能用吗？我们两个端都用的是ijk的。

**Comment by ShikinChen** [comment]
可能等我有空研究一下 而且我太久没做iOS开发需要重新熟悉一下
