### ISSUE TITLE
请问如何编译到so文件

### ISSUE THREAD

**Issue by Warren-W** [ShikinChen/ijkplayer-android#2]

**Comment by ShikinChen** [comment]
你是说将ffmpeg编译成so?好像我尝试过,好像报一些arm64还是armv7一些错,忘记具体是什么,后面还是改回用静态库

**Comment by davikl** [comment]
我说我编译静态库，怎么少这少那
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/aacsbr_template.c:412: error: undefined reference to 'log2f'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/aacsbr_template.c:457: error: undefined reference to 'log2f'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/aacsbr_template.c:604: error: undefined reference to 'log2f'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/mediacodec_surface.c:47: error: undefined reference to 'ANativeWindow_acquire'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/mediacodec_surface.c:73: error: undefined reference to 'ANativeWindow_release'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/mediacodec_wrapper.c:2296: error: undefined reference to 'ANativeWindow_release'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/mediacodec_wrapper.c:2319: error: undefined reference to 'ANativeWindow_fromSurface'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/v4l2_buffers.c:537: error: undefined reference to 'mmap64'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavformat/hls.c:918: error: undefined reference to 'atof'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavformat/hls.c:905: error: undefined reference to 'strtof'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavformat/hlsproto.c:139: error: undefined reference to 'atof'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavutil/file.c:97: error: undefined reference to 'mmap64'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavutil/hwcontext_mediacodec.c:100: error: undefined reference to 'ANativeWindow_release'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavutil/mem.c:105: error: undefined reference to 'posix_memalign'
/home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavutil/arm/cpu.c:58: error: undefined reference to 'getauxval'
clang90: error: linker command failed with exit code 1 (use -v to see invocation)
davik@ubuntu:~/Desktop/ijkplayer-android_ffmpeg6/android/contrib$ cat /home/davik/Desktop/ijkplayer-android_ffmpeg6/extra/ffmpeg/libavcodec/aacsbr_template.c

**Comment by ShikinChen** [comment]
编译时候 export ANDROID_NDK的版本是r27?

**Comment by davikl** [comment]
所有版本都一样 21-27 都试过

**Comment by ShikinChen** [comment]
试下更新一下代码 我在脚本加上 -lm 我在ubuntu 22.04没出现这个问题 我想是不是旧版本ubuntu问题不是最新的glibc问题
