### ISSUE TITLE
ffmpeg动态库编译完之后怎么编译ijk

### ISSUE THREAD

**Issue by davikl** [ShikinChen/ijkplayer-android#3]
ffmpeg动态库编译完之后怎么编译ijk

**Comment by ShikinChen** [comment]
README.md已经增加打包aar的说明,如果需要动态库也在jkplayer-android/android/ijkplayer/ijkplayer-java/build/intermediates/cmake/release/obj/arm64-v8a/生成

**Comment by davikl** [comment]
编译完之后好像没看到 ffmpeg 的 so

**Comment by ShikinChen** [comment]
在ijkplayer-android/android/contrib/build/ffmpeg-arm64/output/lib/这目录 我编译是静态库 编译动态库有问题 主要不知道ffmpeg 6对不同平台的架构交叉编译做什么处理,有时候编译后包括其他架构的obj文件 但是ffmpeg 4没有这个问题 所以b站脚本把编译好的obj文件重新链接一起 但是ffmpeg 6不行,估计也会把一些其他架构obj文件也导进去原因

**Comment by davikl** [comment]
我需要 armv7a 的，现在大多数电视机都是 armv7a的 ，ffmpeg6 编译能降低 ndk 版本到 21 么

**Comment by davikl** [comment]
或者说 ff5.1.4 能用 ndk21 编译么

**Comment by ShikinChen** [comment]
可以用22 ,21当时我是没有判断,现在加上了应该也可以,用./compile-ffmpeg.sh armv7a进行编译就行,项目里面你就改一下gradle的ndk配置,用27只是我as一直用最新版本很多东西尽量适配as,这个项目是支持用21-27的,后面不想这么麻烦直接默认27,而且在mac有21还是22版本的ndk交叉编译脚本是有问题需要执行2次./compile-ffmpeg.sh arm64

**Comment by davikl** [comment]
我尝试用 21 22 编译出来过，但是当 进行 ijk 编译的时候会报错

**Comment by davikl** [comment]
目前正在试着修改 ffmpeg 5 的问题

**Comment by davikl** [comment]
目前正在尝试 ffmpeg 5.1.4 ，ffmpeg 编译 ndk21 ijk 编译  ndk21 会报错

**Comment by ShikinChen** [comment]
试一下更新代码 我更新了ndk21版本编译出错的问题 不过自行修改ijkplayer-java和ijkplayer-example里面的build.gradle相关配置
