### ISSUE TITLE
不支持openssl吗？

### ISSUE THREAD

**Issue by zhangqunshan** [ShikinChen/ijkplayer-android#8]
加上openssl 打包出来的ffmpeg在ijkplayer中打包时，出现：ijk_ffmpeg6.1/extra/ffmpeg/libavformat/tls_openssl.c:156: undefined reference to `SSL_CTX_free'类似这样的错误很多

**Comment by ShikinChen** [comment]
增加了openssl支持,按README.md说明执行脚本重新编译就行
